export const lotData = Object.freeze({
  lot: 'TP-260902-041',
  product: 'Suporte Metálico X-17',
  order: 'PED-1084',
  quantity: '500 unidades',
  customer: 'Cliente demonstrativo',
  status: 'Em expedição',
  statusMessage: 'Dentro do prazo',
  deliveryEstimate: '05/09/2026',
  progress: 87,
  lastUpdate: '02/09/2026 às 14:30',
  qualityOccurrence: {
    title: 'Ocorrência resolvida',
    summary: 'Uma divergência dimensional foi identificada durante a inspeção inicial.',
    resolution:
      'O lote foi corrigido pela Produção e aprovado pela Qualidade após uma nova inspeção.',
  },
  timeline: [
    {
      id: 'order',
      label: 'Pedido confirmado',
      sector: 'Comercial',
      timestamp: '2026-08-28T09:10:00-03:00',
      detail: 'Pedido PED-1084 recebido e especificações validadas.',
      state: 'complete',
    },
    {
      id: 'material',
      label: 'Matéria-prima separada',
      sector: 'Logística interna',
      timestamp: '2026-08-29T07:40:00-03:00',
      detail: 'Aço carbono do lote MP-8821 disponibilizado para produção.',
      state: 'complete',
    },
    {
      id: 'production',
      label: 'Produção iniciada',
      sector: 'Produção',
      timestamp: '2026-08-30T06:15:00-03:00',
      detail: 'Ordem de fabricação liberada para 500 unidades.',
      state: 'complete',
    },
    {
      id: 'cnc',
      label: 'Usinagem CNC concluída',
      sector: 'Produção',
      timestamp: '2026-08-31T18:20:00-03:00',
      detail: 'Processamento concluído na célula CNC-04.',
      state: 'complete',
    },
    {
      id: 'inspection',
      label: 'Inspeção inicial registrada',
      sector: 'Qualidade',
      timestamp: '2026-09-01T08:05:00-03:00',
      detail: 'Divergência dimensional identificada e ocorrência OC-291 aberta.',
      state: 'complete',
      hasOccurrence: true,
    },
    {
      id: 'reinspection',
      label: 'Reinspeção aprovada',
      sector: 'Qualidade',
      timestamp: '2026-09-01T15:10:00-03:00',
      detail: 'Correção realizada; amostra reinspecionada e lote liberado.',
      state: 'complete',
    },
    {
      id: 'packing',
      label: 'Pedido preparado',
      sector: 'Logística',
      timestamp: '2026-09-02T06:45:00-03:00',
      detail: 'Volumes conferidos, identificados e encaminhados à doca 2.',
      state: 'complete',
    },
    {
      id: 'dispatch',
      label: 'Em expedição',
      sector: 'Logística',
      timestamp: '2026-09-02T14:30:00-03:00',
      detail: 'Pedido aguardando coleta da transportadora às 16:00.',
      state: 'current',
    },
  ],
  details: [
    ['Material', 'Aço carbono SAE 1020'],
    ['Dimensões', '120 × 48 × 16 mm'],
    ['Desenho técnico', 'DT-X17 · revisão 06'],
    ['Inspeção', 'Plano PI-X17 · nível II'],
  ],
  documents: [
    { id: 'inspection-certificate', label: 'Certificado de inspeção', meta: 'PDF · Demonstração' },
    { id: 'material-certificate', label: 'Certificado da matéria-prima', meta: 'PDF · Demonstração' },
    { id: 'technical-drawing', label: 'Desenho técnico X-17', meta: 'PDF · Demonstração' },
  ],
});

